Jmbuzano/simple set int
hebench/frontend pull request #72
Opened 2022-10-19 00:54 UTC by jmbuzano

## Proposed changes

Adding Simple Set Intersection (SSI) Workload support

This involves the following elements:
    - Data loading 
    - Data generation
    - SSI related functions and validation
    - Tests

## Types of changes

What types of changes does your code introduce to the HEBench Frontend?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/hebench/frontend/blob/main/CONTRIBUTING.md) doc
- [x] Current formatting and unit tests / base functionality passes locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did, what alternatives you considered, etc.

2022-10-19 06:01 UTC, kylanerace requested changes
Hey Javier. I noticed the CI was failing... seems just formatting for now though. Can you run pre-commit, re-commit the changes, and re-run the CI?

2022-10-19 19:20 UTC, sidezrw requested changes
@jmbuzano , can you merge from `main` and `development` into `jmbuzano/simple_set_int` in your local repo, then push to remote? This will prevent problems when merging the PR into `development` and `main`.

2022-10-20 20:41 UTC, kylanerace approved these changes
lgtm - CI Passed

2022-10-20 20:41 UTC, sidezrw approved these changes

2022-10-20 20:41 UTC, merged